export type User = {
  /**
   * id generated by database
   */
  _id: string;

  /**
   * name
   */
  first_name: string;

  /**
   * surname
   */
  last_name: string;


  /**
   * email for authentication
   */
  email: string;

  /**
   * password for authentication
   */
  password: string;

  /**
   * profile image of users
   */
  image?: string;

  /**
   * date when user is saved in database
   */
  created_at: string;

   /**
   * date when user is updated in database
   */
  updated_at: string;

  /**
   * Role can be:
   * - admin
   * - teacher
   * - user
   */
  role: Role;

  /**
   * Teachers courses. This propriety will be able only for users with "role": teacher
   */
  subjects?: string[];

  /**
   * This propriety will be able only for users with "role": teacher
   */
  classes?: string;

  /**
   * This propriety will be able only for users with "role": student
   */
  student_class?: string;
};

export type  Role = "admin" | "teacher" | "student";